name: checkout
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List file before
              run: ls -la
            - uses: action/checkout@
            - name: List files after
              run: ls -la
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List file before
              run: ls -la
            - name: Checkout
              run: |
                echo $GITHUB_ACTOR
                echo $GITHUB_REPOSITORY

                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GIHTUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List file after
              run: ls -la