name: checkout
on: [push]

jobs:
    checkout-and-display-files:
        runs-on: ubuntu-latest
        steps:
            - name: List file before
              run: ls -la
            - name: Checkout
              run: |
                echo $GITHUB_ACTOR
                echo $GITHUB_REPOSITORY

                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GIHTUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List file after
              run: ls -la

################################
#Output:
# Run echo $GITHUB_ACTOR
# faraz9993                 >>>>>>  echo $GITHUB_ACTOR
# faraz9993/github_action       >>>>>>  echo $GITHUB_REPOSITORY
# hint: Using 'master' as the name for the initial branch. This default branch name
# hint: is subject to change. To configure the initial branch name to use in all
# hint: of your new repositories, which will suppress this warning, call:
# hint:
# hint: 	git config --global init.defaultBranch <name>
# hint:
# hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
# hint: 'development'. The just-created branch can be renamed via this command:
# hint:
# hint: 	git branch -m <name>
# Initialized empty Git repository in /home/runner/work/github_action/github_action/.git/
# From https://github.com/faraz9993/github_action
#  * [new branch]      main       -> origin/main
# Switched to a new branch 'main'
# branch 'main' set up to track 'origin/main'.
##################################