name: checkout
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List file before
              run: ls -la
            - uses: actions/checkout@v3
            - name: in which branch we are
              run: git branch
