name: Docker4
on: [push]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:20.3-alpine3.17
#        if you are using github container registry you would have to put registry name
#       container: ghcr.io/owner/image
            env: 
                API_URL: some-url.com
            ports:
                - 80
            # volumes:
                # - vol_name:/path/in/container
                # - /path/to/container
                # - /path/in/host:/path/in/container
            # options: --cpus 1 
        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log env
              run: echo $API_URL
            - name: Create a file
              run: echo 'Some Text' > text.txt
            - name: Container in a Step
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node
                args: -p 2+3
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: Show file
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt 
            - name: send a slack message
              uses: docker://technosophos/slack-notify
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_TITLE: From GitHub Action
                SLACK_MESSAGE: "Actor: ${{ github.actor }}, Event: ${{ github.event_name }}"
                SLACK_COLOR: "#723fc4"