name: Docker4
on: [push]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:20.3-alpine3.17
#        if you are using github container registry you would have to put registry name
#       container: ghcr.io/owner/image
            env: 
                API_URL: some-url.com
            ports:
                - 80
            # volumes:
                # - vol_name:/path/in/container
                # - /path/to/container
                # - /path/in/host:/path/in/container
            # options: --cpus 1 
        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log env
              run: echo $API_URL
            - name: Create a file
              run: echo 'Some Text' > text.txt
            - name: Container in a Step
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node
                args: -p 2+3
            - name: Log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: Show file
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt 
            - uses: actions/checkout@v3
            - name: Run a bash script
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: |
                    chmod 777 ./script.sh
                    sh script.sh
                args: "Some String"