name: Docker
on: [push]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:20.3-alpine3.17
#        if you are using github container registry you would have to put registry name
#       container: ghcr.io/owner/image
            env: 
                API_URL: some-url.com
            ports:
                - 80
            # volumes:
                # - vol_name:/path/in/container
                # - /path/to/container
                # - /path/in/host:/path/in/container
            # options: --cpus 1 
        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log env
              run: echo $API_URL
