name: Repository Events
on:
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]     
jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - name: print the details
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3