name: Palash_Workflow_3

on:
  push:
    branches:
      - main  
  workflow_dispatch:  
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "This is Workflow_3"
