name: Status Check Function
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
          - name: Step 1
            run: sleep 20
          - name: Runs on Failure
            if: failure()
            run: echo 'Runs only on failure'
          - name: Runs on success
            if: success()
            run: echo 'Runs on success'
          - name: Always runs
            if: always()    # you can also write here "if: success() || failure()"
            run: echo 'Always Runs'
          - name: Runs when cancelled
            if: cancelled()
            run: echo 'Runs on Cancelled'
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if: failure()
        steps:
          - run: echo 'Job 2'