name: Calling Reusable Workflow
on:
    workflow_dispatch:
        inputs:
            name:
                description: 'Input description'
                type: string
                default: 'Faraz'
                required: false
jobs:
    calling-a-reusable-wf:
        uses: github_action/workflows/.github/workflows/reusable.yaml@main
        with:
            name: ${{ inputs.name }}
        secrets: 
            access-token: ${{ secrets.ACCESS_TOKEN }}
